version: "3.9"
services:

  database:
    image: postgres
    container_name: database_finapi
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=rentx
      - POSTGRES_DB=finapi
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: finapi
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database


volumes:
  pgdata:
    driver: local
    